SET autocommit = 0;

START TRANSACTION;

INSERT INTO dish_type (id_type, name_type) VALUES ('7', 'TTTTr');

SELECT * FROM dish_type;

ROLLBACK;

SELECT * FROM dish_type;

START TRANSACTION;

INSERT INTO dish_type (id_type, name_type) VALUES ('8', 'TTTTr');

SELECT * FROM dish_type;

COMMIT;

SELECT * FROM dish_type;

# 1 уровень изоляции READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT * FROM dish_type;

# данные
SELECT * FROM dish_type;

COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM dish_type;

# 2 данные
SELECT * FROM dish_type;

COMMIT;

# REPEATABLE READ(READ COMMITTED)
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM dish_type;

SELECT * FROM dish_type;
COMMIT;
# -- --
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT * FROM dish_type;

SELECT * FROM dish_type;
COMMIT;